import {
  breadcrumbSchema,
  faqSchema,
  jsonLd,
  softwareApplicationSchema,
} from '@/lib/ai-visibility-schema';
import { seo } from '@/lib/seo';
import { getCanonicalUrl } from '@/lib/urls';
import { trackConversionEvent } from '@/lib/conversion-events';
import { createFileRoute } from '@tanstack/react-router';
import Container from '@/components/layout/container';
import { FAQ } from '@/components/ai-visibility/faq';
import {
  IconCheck,
  IconX,
  IconAlertTriangle,
  IconLoader2,
  IconMail,
  IconCopy,
  IconDownload,
  IconArrowRight,
  IconSearch,
  IconFileText,
  IconShield,
  IconCode,
  IconMessageCircle,
  IconUserCheck,
  IconChartBar,
  IconExternalLink,
} from '@tabler/icons-react';
import { runAeoAudit, type AeoAuditResult } from '@/api/ai-readiness/aeo';
import { submitLeadCapture } from '@/api/ai-readiness/lead';
import { createReportCheckout } from '@/api/ai-readiness/report-checkout';
import { useState, useEffect, useRef } from 'react';

// ---------- Types ----------

type Status = 'good' | 'warning' | 'issue' | 'neutral';

// ---------- Utility helpers ----------

function statusBadge(status: Status) {
  const map: Record<Status, { bg: string; text: string; icon: string }> = {
    good: {
      bg: 'bg-emerald-100 dark:bg-emerald-900/30',
      text: 'text-emerald-700 dark:text-emerald-400',
      icon: 'text-emerald-500',
    },
    warning: {
      bg: 'bg-amber-100 dark:bg-amber-900/30',
      text: 'text-amber-700 dark:text-amber-400',
      icon: 'text-amber-500',
    },
    issue: {
      bg: 'bg-red-100 dark:bg-red-900/30',
      text: 'text-red-700 dark:text-red-400',
      icon: 'text-red-500',
    },
    neutral: {
      bg: 'bg-gray-100 dark:bg-zinc-800',
      text: 'text-gray-600 dark:text-zinc-400',
      icon: 'text-gray-400',
    },
  };
  return map[status];
}

function accessBadge(access: string) {
  switch (access) {
    case 'allowed':
      return {
        label: 'Allowed',
        cls: 'text-emerald-600 dark:text-emerald-400',
      };
    case 'blocked':
      return { label: 'Blocked', cls: 'text-red-600 dark:text-red-400' };
    default:
      return { label: 'Unknown', cls: 'text-gray-400 dark:text-zinc-500' };
  }
}

function scoreColor(score: number): string {
  if (score >= 80) return '#10b981';
  if (score >= 60) return '#f59e0b';
  return '#ef4444';
}

const scoreLabels: Record<string, string> = {
  '80-100': 'Strong technical AEO readiness',
  '60-79': 'Good foundation with improvement opportunities',
  '40-59': 'Partial readiness, several important gaps',
  '0-39': 'Weak technical AEO readiness',
};

function scoreLabelText(score: number): string {
  if (score >= 80) return scoreLabels['80-100'];
  if (score >= 60) return scoreLabels['60-79'];
  if (score >= 40) return scoreLabels['40-59'];
  return scoreLabels['0-39'];
}

function formatYesNo(value: boolean): string {
  return value ? 'Yes' : 'No';
}

function buildFreeReportMarkdown(result: AeoAuditResult): string {
  const topIssues = result.recommendations.slice(0, 3);
  const lines = [
    '# Free AI Search Readiness Audit',
    '',
    `Website: ${new URL(result.normalizedUrl).hostname}`,
    `Checked URL: ${result.normalizedUrl}`,
    `Generated at: ${new Date(result.checkedAt).toISOString()}`,
    `Overall Score: ${result.score}/100`,
    `Readiness: ${result.scoreLabel}`,
    '',
    '## Executive Summary',
    '',
    `This free summary shows the technical AEO score, key module status, and the top ${topIssues.length} recommended fixes. It is a technical readiness estimate and does not guarantee rankings, citations, traffic, or visibility in any AI search product.`,
    '',
    '## Top Issues',
    '',
    ...(topIssues.length > 0
      ? topIssues.map((issue, index) => `${index + 1}. ${issue}`)
      : ['No major recommendations were generated by the free checker.']),
    '',
    '## Technical AEO Audit',
    '',
    `- HTTP status: ${result.page.statusCode ? `HTTP ${result.page.statusCode}` : 'Unknown'}`,
    `- Title: ${result.page.title || 'Missing'}`,
    `- Meta description: ${result.page.metaDescription || 'Missing'}`,
    `- Canonical: ${result.page.canonical || 'Missing'}`,
    `- Meta robots: ${result.page.metaRobots || 'Not detected'}`,
    '',
    '## AI Search Files Audit',
    '',
    `- LLMs.txt: ${formatYesNo(result.aiFiles.llmsTxt.exists)}`,
    `- LLMs-full.txt: ${formatYesNo(result.aiFiles.llmsFullTxt.exists)}`,
    `- Sitemap.xml: ${formatYesNo(result.aiFiles.sitemap.exists)}`,
    `- Robots.txt: ${formatYesNo(result.aiFiles.robotsTxt.exists)}`,
    '',
    '## Answer-Ready Content Audit',
    '',
    `- H1 count: ${result.answerReadyContent.h1Count}`,
    `- H2 count: ${result.answerReadyContent.h2Count}`,
    `- FAQ section: ${formatYesNo(result.answerReadyContent.hasFaqSection)}`,
    `- Question headings: ${formatYesNo(result.answerReadyContent.hasQuestionHeadings)}`,
    `- Short answer paragraphs: ${formatYesNo(result.answerReadyContent.hasShortAnswerParagraphs)}`,
    '',
    '## Locked Fix Pack Sections',
    '',
    '- Full issue list',
    '- Prioritized repair order',
    '- Copy-ready schema recommendations',
    '- Answer-ready content rewrite suggestions',
    '- Query fan-out content gap analysis',
    '- LLMs.txt improvement plan',
    '- Downloadable implementation handoff',
    '',
    'These tools provide technical readiness checks. They do not guarantee rankings, citations, traffic, or visibility in ChatGPT, Perplexity, Gemini, Claude, Google AI Overviews, or other AI search products.',
  ];
  return lines.join('\n');
}

// ---------- FAQ items ----------

const faqItems = [
  {
    q: 'What is AEO?',
    a: 'AEO stands for Answer Engine Optimization. It is the practice of optimizing your website content and technical foundations so that answer engines and AI search systems can better understand, extract, and cite your pages.',
  },
  {
    q: 'What does an AEO checker do?',
    a: 'An AEO checker audits your website for the technical and content signals that help answer engines understand your pages. It checks crawlability, structured data, LLMs.txt files, AI crawler access, content structure, entity clarity, and trust signals.',
  },
  {
    q: 'Does this tool check ChatGPT rankings?',
    a: 'No. This tool audits technical AEO readiness signals. It does not check whether your brand appears in ChatGPT, Perplexity, or any other AI search product, and does not track rankings or citations.',
  },
  {
    q: 'What is a good AEO score?',
    a: 'A score of 80 or above indicates strong technical readiness. 60-79 shows a good foundation with room to improve. Below 60 means there are several gaps worth addressing. The score is a technical estimate, not a ranking guarantee.',
  },
  {
    q: 'Does LLMs.txt improve AEO?',
    a: 'An LLMs.txt file gives AI systems a structured summary of your site. It is one component of AEO readiness, alongside structured data, crawlability, and content formatting. It helps, but it is not the whole picture.',
  },
  {
    q: 'What structured data helps AEO?',
    a: 'JSON-LD schema types like Organization, WebSite, Article, FAQPage, Product, and HowTo help answer engines understand what your pages are about. The checker identifies which schema types are present and recommends additions.',
  },
  {
    q: 'How is AEO different from SEO?',
    a: 'SEO optimizes for search engine rankings and traffic. AEO optimizes for answer engine understanding and citation. They overlap but are not the same. A page can rank well on Google but still not be structured well for AI extraction.',
  },
];

// ---------- Dashboard Preview (shown before audit) ----------

const previewSidebarWidths = [78, 64, 86, 72, 82, 68];

function DashboardPreview() {
  return (
    <div
      className="mx-auto mt-12 max-w-4xl animate-fade-up delay-3"
      aria-hidden="true"
    >
      <p className="mb-4 text-center text-xs font-semibold uppercase tracking-wider text-muted-foreground">
        Dashboard preview
      </p>
      <div className="overflow-hidden rounded-2xl border border-border/60 bg-card shadow-sm">
        {/* Top bar */}
        <div className="flex items-center gap-3 border-b border-border/40 px-4 py-2.5">
          <div className="flex items-center gap-1.5 rounded-lg border border-border/50 bg-muted/40 px-3 py-1.5 text-xs text-muted-foreground w-64">
            <IconSearch size={12} />
            <span>example.com/page</span>
          </div>
          <div className="ml-auto h-2 w-20 rounded-full bg-muted/60" />
        </div>
        {/* Sidebar + Main */}
        <div className="flex">
          {/* Left sidebar */}
          <div className="hidden sm:block w-40 shrink-0 border-r border-border/40 p-3 space-y-2">
            {previewSidebarWidths.map((width, i) => (
              <div
                key={i}
                className="h-2 rounded bg-muted/50"
                style={{ width: `${width}%` }}
              />
            ))}
          </div>
          {/* Main content */}
          <div className="flex-1 p-4 space-y-4">
            {/* Score card */}
            <div className="rounded-xl border border-border/40 bg-muted/20 p-4">
              <div className="flex items-center gap-4">
                <div className="size-16 rounded-full border-4 border-muted/40 flex items-center justify-center">
                  <span className="text-xl font-bold text-muted-foreground/40">
                    --
                  </span>
                </div>
                <div>
                  <div className="h-3 w-32 rounded bg-muted/40" />
                  <div className="mt-1.5 h-2 w-48 rounded bg-muted/30" />
                </div>
              </div>
            </div>
            {/* Module grid */}
            <div className="grid gap-3 md:grid-cols-2">
              {[
                { label: 'Crawl access', icon: IconSearch },
                { label: 'LLMs.txt', icon: IconFileText },
                { label: 'Structured data', icon: IconCode },
                { label: 'Answer blocks', icon: IconMessageCircle },
                { label: 'Trust signals', icon: IconShield },
                { label: 'Repair priority', icon: IconChartBar },
              ].map((mod) => (
                <div
                  key={mod.label}
                  className="flex items-center gap-2.5 rounded-lg border border-border/40 bg-muted/20 p-3"
                >
                  <mod.icon size={14} className="text-muted-foreground/40" />
                  <span className="text-xs text-muted-foreground/60">
                    {mod.label}
                  </span>
                  <div className="ml-auto h-1.5 w-12 rounded-full bg-muted/40" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---------- Score Ring ----------

function ScoreRing({ score, animate }: { score: number; animate: boolean }) {
  const [displayScore, setDisplayScore] = useState(animate ? 0 : score);
  const color = scoreColor(score);
  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const progress = (displayScore / 100) * circumference;

  useEffect(() => {
    if (!animate) return;
    const prefersReduced = window.matchMedia(
      '(prefers-reduced-motion: reduce)'
    ).matches;
    if (prefersReduced) {
      setDisplayScore(score);
      return;
    }
    let frame: number;
    const start = performance.now();
    const duration = 1200;
    const tick = (now: number) => {
      const elapsed = now - start;
      const t = Math.min(elapsed / duration, 1);
      const eased = 1 - (1 - t) ** 3;
      setDisplayScore(Math.round(eased * score));
      if (t < 1) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [score, animate]);

  return (
    <div className="relative inline-flex items-center justify-center">
      <svg width="140" height="140" className="-rotate-90">
        <circle
          cx="70"
          cy="70"
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth="8"
          className="text-muted/20"
        />
        <circle
          cx="70"
          cy="70"
          r={radius}
          fill="none"
          stroke={color}
          strokeWidth="8"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={circumference - progress}
          className="transition-[stroke-dashoffset] duration-700 ease-out"
        />
      </svg>
      <span className="absolute text-3xl font-bold" style={{ color }}>
        {displayScore}
      </span>
    </div>
  );
}

// ---------- Dashboard Sidebar Nav ----------

const dashboardSections = [
  { id: 'score', label: 'Readiness Score', icon: IconChartBar },
  { id: 'crawl', label: 'Crawlability', icon: IconSearch },
  { id: 'files', label: 'AI Search Files', icon: IconFileText },
  { id: 'schema', label: 'Structured Data', icon: IconCode },
  { id: 'content', label: 'Answer Content', icon: IconMessageCircle },
  { id: 'entity', label: 'Entity Clarity', icon: IconUserCheck },
  { id: 'trust', label: 'Trust Signals', icon: IconShield },
  { id: 'fixes', label: 'Repair Plan', icon: IconAlertTriangle },
];

function DashboardSidebar({
  activeSection,
  onNavigate,
}: {
  activeSection: string;
  onNavigate: (id: string) => void;
}) {
  return (
    <nav className="hidden lg:block w-52 shrink-0">
      <div className="sticky top-28 space-y-1">
        <p className="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
          Audit sections
        </p>
        {dashboardSections.map((section) => (
          <button
            key={section.id}
            type="button"
            onClick={() => onNavigate(section.id)}
            className={`flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-sm transition-colors text-left ${
              activeSection === section.id
                ? 'bg-accent font-medium text-accent-foreground'
                : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'
            }`}
          >
            <section.icon size={15} />
            {section.label}
          </button>
        ))}
      </div>
    </nav>
  );
}

// ---------- Main Component ----------

function AeoCheckerPage() {
  const [url, setUrl] = useState(() => {
    if (typeof window === 'undefined') return '';
    return new URLSearchParams(window.location.search).get('url') ?? '';
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AeoAuditResult | null>(null);
  const [leadEmail, setLeadEmail] = useState('');
  const [leadWebsiteUrl, setLeadWebsiteUrl] = useState('');
  const [leadLoading, setLeadLoading] = useState(false);
  const [leadMessage, setLeadMessage] = useState<string | null>(null);
  const [leadSuccess, setLeadSuccess] = useState(false);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [reportMessage, setReportMessage] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState('score');
  const [scoreAnimated, setScoreAnimated] = useState(false);
  const resultsRef = useRef<HTMLDivElement>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = url.trim();
    if (!trimmed) {
      setError('Please enter a domain or page URL.');
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    setScoreAnimated(false);
    trackConversionEvent('aeo_audit_started', { url: trimmed });
    try {
      const data = await runAeoAudit({ data: { url: trimmed } });
      setResult(data);
      setLeadWebsiteUrl(data.normalizedUrl);
      setLeadMessage(null);
      setScoreAnimated(true);
      setActiveSection('score');
      trackConversionEvent('aeo_audit_completed', {
        url: data.normalizedUrl,
        score: data.score,
      });
      setTimeout(() => {
        resultsRef.current?.scrollIntoView({
          behavior: 'smooth',
          block: 'start',
        });
      }, 100);
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : 'Something went wrong. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  const handleLeadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!leadEmail.trim() || !leadWebsiteUrl.trim() || !result) return;
    setLeadLoading(true);
    setLeadMessage(null);
    try {
      const res = await submitLeadCapture({
        data: {
          email: leadEmail.trim(),
          websiteUrl: leadWebsiteUrl.trim(),
        },
      });
      setLeadMessage(res.message);
      setLeadSuccess(res.success);
      if (res.success) {
        trackConversionEvent('aeo_lead_capture_submitted', {
          url: leadWebsiteUrl.trim(),
        });
        setLeadEmail('');
      }
    } catch {
      setLeadMessage(
        'Unable to send the report at this time. Please try again later.'
      );
      setLeadSuccess(false);
    } finally {
      setLeadLoading(false);
    }
  };

  const handleCheckout = async () => {
    if (!result) return;
    setCheckoutLoading(true);
    setReportMessage(null);
    trackConversionEvent('full_report_checkout_clicked', {
      url: result.normalizedUrl,
      score: result.score,
      price: 19,
    });
    try {
      const res = await createReportCheckout({
        data: {
          resultJson: JSON.stringify(result),
          websiteUrl: result.normalizedUrl,
        },
      });
      if (res.url) {
        trackConversionEvent('full_report_checkout_redirected', {
          url: result.normalizedUrl,
        });
        window.location.href = res.url;
      } else {
        setReportMessage(
          'Payment service returned an empty URL. Please try again.'
        );
        setCheckoutLoading(false);
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown error';
      setReportMessage(`Checkout failed: ${msg}`);
      setCheckoutLoading(false);
    }
  };

  const handleCopySummary = async () => {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(buildFreeReportMarkdown(result));
      setReportMessage('Free report summary copied.');
    } catch {
      setReportMessage('Unable to copy the report summary.');
    }
  };

  const handleDownloadSummary = () => {
    if (!result) return;
    const markdown = buildFreeReportMarkdown(result);
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const href = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = href;
    link.download = `ai-search-readiness-summary-${
      new URL(result.normalizedUrl).hostname
    }.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(href);
    setReportMessage('Free report summary downloaded.');
  };

  const r = result;

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden border-b border-border/50">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50/50 via-background to-background dark:from-blue-950/20 dark:via-background dark:to-background" />
        <Container className="relative py-16 lg:py-24">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="animate-fade-up text-3xl font-bold tracking-tight text-foreground sm:text-4xl lg:text-5xl">
              Audit one page before AI search edits
            </h1>
            <p className="animate-fade-up delay-1 mx-auto mt-4 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">
              Check crawl access, schema, answer blocks, LLMs.txt, and trust
              gaps before you spend time rewriting the page.
            </p>
            {/* Inline form */}
            <form
              onSubmit={handleSubmit}
              className="animate-fade-up delay-2 mx-auto mt-8 max-w-xl"
            >
              <div className="flex gap-3">
                <div className="relative flex-1">
                  <IconSearch
                    size={16}
                    className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground/60"
                  />
                  <input
                    type="text"
                    placeholder="Enter the page URL you plan to fix"
                    value={url}
                    onChange={(e) => setUrl(e.target.value)}
                    disabled={loading}
                    className="w-full rounded-xl border border-border bg-background pl-10 pr-4 py-3 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-50"
                  />
                </div>
                <button
                  type="submit"
                  disabled={loading}
                  className="inline-flex items-center gap-2 rounded-xl bg-foreground px-6 py-3 text-sm font-semibold text-background transition-all hover:opacity-90 active:scale-[0.98] disabled:opacity-50"
                >
                  {loading ? (
                    <>
                      <IconLoader2 size={16} className="animate-spin" />{' '}
                      Auditing...
                    </>
                  ) : (
                    'Run free page audit'
                  )}
                </button>
              </div>
              <p className="mt-3 text-center text-xs text-muted-foreground">
                Free result: score, module status, and top issues. $19 Fix Pack:
                copy-ready repair assets and implementation handoff.
              </p>
            </form>
          </div>

          {/* Dashboard preview (before audit) */}
          {!r && !loading && <DashboardPreview />}
        </Container>
      </section>

      {/* Error */}
      {error && (
        <section className="py-6">
          <Container>
            <div className="mx-auto max-w-xl rounded-2xl border border-red-200 dark:border-red-900/30 bg-red-50 dark:bg-red-950/20 p-4 text-center">
              <p className="text-sm text-red-700 dark:text-red-400">{error}</p>
            </div>
          </Container>
        </section>
      )}

      {/* Loading */}
      {loading && !r && (
        <section className="py-20">
          <Container>
            <div className="mx-auto max-w-xl rounded-2xl border border-border/60 bg-muted/20 p-10 text-center">
              <IconLoader2
                size={48}
                className="mx-auto animate-spin text-primary"
              />
              <p className="mt-4 text-sm text-muted-foreground">
                Auditing your page. This may take a few seconds.
              </p>
            </div>
          </Container>
        </section>
      )}

      {/* Pre-audit info (only shown before audit) */}
      {!r && !loading && !error && (
        <>
          <section className="py-16">
            <Container>
              <div className="mx-auto max-w-3xl text-center">
                <h2 className="text-2xl font-bold text-foreground">
                  From audit score to page repair
                </h2>
                <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
                  Traditional SEO tools tell you rankings, links, and keywords.
                  This checker focuses on the page-level structure AI answer
                  systems need before they can understand your content: crawl
                  access, schema, concise answers, entity clarity, trust pages,
                  and AI-readable files.
                </p>
                <div className="mt-8 grid gap-3 md:grid-cols-3">
                  {[
                    {
                      title: 'Before publishing',
                      desc: 'Confirm crawlers, schema, headings, FAQs, and trust signals before the page starts competing.',
                    },
                    {
                      title: 'Before refreshing',
                      desc: 'Find whether the page gives answer engines direct answers before you rewrite it.',
                    },
                    {
                      title: 'Before handing off',
                      desc: 'Unlock the Fix Pack for copy-ready schema, content gaps, and a prioritized repair order.',
                    },
                  ].map((item) => (
                    <div
                      key={item.title}
                      className="rounded-xl border border-border/60 bg-muted/20 p-5 text-left"
                    >
                      <h3 className="text-sm font-semibold text-foreground">
                        {item.title}
                      </h3>
                      <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
                        {item.desc}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </Container>
          </section>
        </>
      )}

      {/* Results Dashboard */}
      {r && (
        <div ref={resultsRef} className="border-t border-border/50">
          <Container className="py-10">
            <div className="flex gap-8">
              {/* Sidebar */}
              <DashboardSidebar
                activeSection={activeSection}
                onNavigate={(id) => {
                  setActiveSection(id);
                  document
                    .getElementById(`audit-${id}`)
                    ?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }}
              />

              {/* Main content */}
              <div className="flex-1 min-w-0 space-y-8">
                {/* Top toolbar */}
                <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border/60 bg-muted/20 px-4 py-2.5">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <IconSearch size={14} />
                    <span className="truncate max-w-[300px]">
                      {r.normalizedUrl}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span>
                      Checked: {new Date(r.checkedAt).toLocaleString()}
                    </span>
                    <a
                      href={r.normalizedUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 text-primary hover:underline"
                    >
                      Open page <IconExternalLink size={12} />
                    </a>
                  </div>
                </div>

                {/* Score section */}
                <section id="audit-score">
                  <DashboardCard>
                    <div className="flex flex-col items-center gap-6 sm:flex-row sm:items-start">
                      <ScoreRing score={r.score} animate={scoreAnimated} />
                      <div className="text-center sm:text-left">
                        <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                          AI Search Readiness Score
                        </p>
                        <p className="mt-1 text-lg font-semibold text-foreground">
                          {scoreLabelText(r.score)}
                        </p>
                        <p className="mt-2 max-w-md text-sm text-muted-foreground">
                          This score is a technical readiness estimate based on
                          crawl access, AI files, structured data, content
                          structure, entity clarity, and trust signals. It does
                          not guarantee rankings or citations.
                        </p>
                        <div className="mt-4 flex flex-wrap gap-2">
                          {[
                            {
                              label: 'Critical',
                              count: r.recommendations.length,
                              color:
                                'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
                            },
                            {
                              label: 'Warnings',
                              count:
                                r.page.warnings.length +
                                r.structuredData.warnings.length +
                                r.answerReadyContent.warnings.length,
                              color:
                                'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
                            },
                            {
                              label: 'Passed',
                              count: [
                                r.page.statusCode,
                                r.aiFiles.llmsTxt.exists,
                                r.structuredData.hasJsonLd,
                                r.answerReadyContent.hasFaqSection,
                                r.trustSignals.hasAuthor,
                              ].filter(Boolean).length,
                              color:
                                'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
                            },
                          ].map((stat) => (
                            <span
                              key={stat.label}
                              className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium ${stat.color}`}
                            >
                              {stat.label}: {stat.count}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                  </DashboardCard>
                </section>

                {/* Crawlability */}
                <section id="audit-crawl">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Technical Crawlability"
                      status="good"
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-3">
                      <Meta
                        label="Status"
                        value={
                          r.page.statusCode
                            ? `HTTP ${r.page.statusCode}`
                            : 'N/A'
                        }
                      />
                      <Meta
                        label="Content Type"
                        value={r.page.contentType || 'N/A'}
                      />
                      <Meta label="Title" value={r.page.title || 'N/A'} />
                      <Meta
                        label="Meta Description"
                        value={r.page.metaDescription || 'N/A'}
                      />
                      <Meta
                        label="Canonical"
                        value={r.page.canonical || 'N/A'}
                      />
                      <Meta
                        label="Meta Robots"
                        value={r.page.metaRobots || 'N/A'}
                      />
                    </div>
                    {r.page.warnings.length > 0 && (
                      <IssueList
                        items={r.page.warnings}
                        type="warning"
                        className="mt-4"
                      />
                    )}
                  </DashboardCard>
                </section>

                {/* AI Files */}
                <section id="audit-files">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="AI Search Files & Crawler Access"
                      status={r.aiFiles.llmsTxt.exists ? 'good' : 'issue'}
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
                      <Meta
                        label="LLMs.txt"
                        value={
                          r.aiFiles.llmsTxt.exists
                            ? `Found (${r.aiFiles.llmsTxt.statusCode})`
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="LLMs-full.txt"
                        value={
                          r.aiFiles.llmsFullTxt.exists
                            ? `Found (${r.aiFiles.llmsFullTxt.statusCode})`
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Sitemap"
                        value={
                          r.aiFiles.sitemap.exists
                            ? `Found (${r.aiFiles.sitemap.statusCode})`
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Robots.txt"
                        value={
                          r.aiFiles.robotsTxt.exists
                            ? `Found (${r.aiFiles.robotsTxt.statusCode})`
                            : 'Not Found'
                        }
                      />
                    </div>
                    {r.aiFiles.robotsTxt.exists && (
                      <div className="mt-4 overflow-x-auto">
                        <table className="w-full text-sm">
                          <thead>
                            <tr className="border-b border-border">
                              <th className="py-2 text-left font-medium text-muted-foreground">
                                Crawler
                              </th>
                              <th className="py-2 text-left font-medium text-muted-foreground">
                                User Agent
                              </th>
                              <th className="py-2 text-right font-medium text-muted-foreground">
                                Access
                              </th>
                            </tr>
                          </thead>
                          <tbody>
                            {r.aiFiles.robotsTxt.crawlers.map((c) => {
                              const b = accessBadge(c.access);
                              return (
                                <tr
                                  key={c.userAgent}
                                  className="border-b border-border/50"
                                >
                                  <td className="py-2.5 text-foreground">
                                    {c.name}
                                  </td>
                                  <td className="py-2.5 font-mono text-xs text-muted-foreground">
                                    {c.userAgent}
                                  </td>
                                  <td
                                    className={`py-2.5 text-right font-medium ${b.cls}`}
                                  >
                                    {b.label}
                                  </td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </DashboardCard>
                </section>

                {/* Structured Data */}
                <section id="audit-schema">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Structured Data"
                      status={r.structuredData.hasJsonLd ? 'good' : 'issue'}
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm">
                      <Meta
                        label="JSON-LD"
                        value={
                          r.structuredData.hasJsonLd ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="Schema Types"
                        value={
                          r.structuredData.schemaTypes.length > 0
                            ? r.structuredData.schemaTypes.join(', ')
                            : 'None'
                        }
                      />
                    </div>
                    {r.structuredData.parseErrors.length > 0 && (
                      <IssueList
                        items={r.structuredData.parseErrors}
                        type="error"
                        className="mt-4"
                      />
                    )}
                    {r.structuredData.warnings.length > 0 && (
                      <IssueList
                        items={r.structuredData.warnings}
                        type="warning"
                        className="mt-2"
                      />
                    )}
                  </DashboardCard>
                </section>

                {/* Answer-ready Content */}
                <section id="audit-content">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Answer-ready Content"
                      status={
                        r.answerReadyContent.hasFaqSection ? 'good' : 'warning'
                      }
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
                      <Meta
                        label="H1 Count"
                        value={String(r.answerReadyContent.h1Count)}
                      />
                      <Meta
                        label="H2 Count"
                        value={String(r.answerReadyContent.h2Count)}
                      />
                      <Meta
                        label="H3 Count"
                        value={String(r.answerReadyContent.h3Count)}
                      />
                      <Meta
                        label="FAQ Section"
                        value={
                          r.answerReadyContent.hasFaqSection
                            ? 'Found'
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Question Headings"
                        value={
                          r.answerReadyContent.hasQuestionHeadings
                            ? 'Found'
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Lists"
                        value={
                          r.answerReadyContent.hasLists
                            ? 'Present'
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Short Answer Paragraphs"
                        value={
                          r.answerReadyContent.hasShortAnswerParagraphs
                            ? 'Present'
                            : 'Not Found'
                        }
                      />
                    </div>
                    {r.answerReadyContent.issues.length > 0 && (
                      <IssueList
                        items={r.answerReadyContent.issues}
                        type="error"
                        className="mt-4"
                      />
                    )}
                    {r.answerReadyContent.warnings.length > 0 && (
                      <IssueList
                        items={r.answerReadyContent.warnings}
                        type="warning"
                        className="mt-2"
                      />
                    )}
                  </DashboardCard>
                </section>

                {/* Entity Clarity */}
                <section id="audit-entity">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Entity Clarity"
                      status="warning"
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
                      <Meta
                        label="Inferred Brand"
                        value={r.entityClarity.inferredBrandName || 'N/A'}
                      />
                      <Meta
                        label="og:site_name"
                        value={
                          r.entityClarity.hasOgSiteName ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="Organization Schema"
                        value={
                          r.entityClarity.hasOrganizationSchema
                            ? 'Found'
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Brand Mentions"
                        value={String(r.entityClarity.brandMentionCount ?? 0)}
                      />
                    </div>
                    {r.entityClarity.issues.length > 0 && (
                      <IssueList
                        items={r.entityClarity.issues}
                        type="error"
                        className="mt-4"
                      />
                    )}
                  </DashboardCard>
                </section>

                {/* Trust Signals */}
                <section id="audit-trust">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Trust Signals"
                      status={r.trustSignals.hasAuthor ? 'good' : 'issue'}
                    />
                    <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
                      <Meta
                        label="Author"
                        value={r.trustSignals.hasAuthor ? 'Found' : 'Not Found'}
                      />
                      <Meta
                        label="Published Date"
                        value={
                          r.trustSignals.hasPublishedDate
                            ? 'Found'
                            : 'Not Found'
                        }
                      />
                      <Meta
                        label="Modified Date"
                        value={
                          r.trustSignals.hasModifiedDate ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="About Link"
                        value={
                          r.trustSignals.hasAboutLink ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="Contact Link"
                        value={
                          r.trustSignals.hasContactLink ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="Privacy Link"
                        value={
                          r.trustSignals.hasPrivacyLink ? 'Found' : 'Not Found'
                        }
                      />
                      <Meta
                        label="External Links"
                        value={String(r.trustSignals.externalLinkCount)}
                      />
                    </div>
                    {r.trustSignals.issues.length > 0 && (
                      <IssueList
                        items={r.trustSignals.issues}
                        type="error"
                        className="mt-4"
                      />
                    )}
                  </DashboardCard>
                </section>

                {/* Recommendations */}
                <section id="audit-fixes">
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="Repair Priority"
                      status="neutral"
                    />
                    <p className="mb-4 text-sm text-muted-foreground">
                      Recommended fixes, ordered by impact on AI search
                      readiness.
                    </p>
                    <ol className="space-y-3">
                      {r.recommendations.map((rec, i) => (
                        <li
                          key={rec}
                          className="flex items-start gap-3 rounded-lg border border-border/60 bg-muted/20 p-3"
                        >
                          <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">
                            {i + 1}
                          </span>
                          <span className="text-sm text-foreground">{rec}</span>
                        </li>
                      ))}
                    </ol>
                  </DashboardCard>
                </section>

                {/* AI Preview */}
                {r.aiAnalysis && (
                  <DashboardCard>
                    <DashboardSectionHeader
                      title="AI Analysis Preview"
                      status="neutral"
                    />
                    <p className="text-sm text-foreground">
                      {r.aiAnalysis.summary}
                    </p>
                    {r.aiAnalysis.quickWins.length > 0 && (
                      <div className="mt-4 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm">
                        <h4 className="font-medium text-primary">
                          One quick win
                        </h4>
                        <p className="mt-1 text-muted-foreground">
                          {r.aiAnalysis.quickWins[0]}
                        </p>
                      </div>
                    )}
                  </DashboardCard>
                )}

                {/* Export */}
                <div className="rounded-2xl border border-border/60 bg-card p-6">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                      <h3 className="font-semibold text-foreground">
                        Free report export
                      </h3>
                      <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
                        Copy or download the free Markdown summary. The full
                        report structure is prepared, but detailed fixes, query
                        fan-out content gaps, and full export remain behind the
                        $19 Fix Pack.
                      </p>
                    </div>
                    <div className="flex shrink-0 flex-col gap-2 sm:flex-row">
                      <button
                        type="button"
                        onClick={handleCopySummary}
                        className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-muted/40 px-4 py-2.5 text-sm font-medium text-foreground transition-all hover:border-border/80 active:scale-[0.98]"
                      >
                        <IconCopy size={16} />
                        Copy summary
                      </button>
                      <button
                        type="button"
                        onClick={handleDownloadSummary}
                        className="inline-flex items-center justify-center gap-2 rounded-xl bg-foreground px-4 py-2.5 text-sm font-semibold text-background transition-all hover:opacity-90 active:scale-[0.98]"
                      >
                        <IconDownload size={16} />
                        Download Markdown
                      </button>
                    </div>
                  </div>
                  {reportMessage ? (
                    <p className="mt-3 text-sm text-muted-foreground">
                      {reportMessage}
                    </p>
                  ) : null}
                </div>

                {/* Fix Pack CTA */}
                <div className="rounded-2xl border border-primary/20 bg-primary/5 p-8 text-center">
                  <h3 className="text-xl font-bold text-foreground">
                    Turn this scan into a repair plan for $19
                  </h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    We found {r.recommendations.length} issues on this page. The
                    Fix Pack turns the diagnosis into prioritized edits,
                    copy-ready schema, LLMs.txt guidance, answer blocks, and
                    query fan-out gaps.
                  </p>

                  <div className="mt-6 overflow-x-auto">
                    <table className="w-full text-sm text-left">
                      <thead>
                        <tr className="border-b border-primary/20">
                          <th className="py-2 font-medium text-muted-foreground">
                            Feature
                          </th>
                          <th className="py-2 text-center font-medium text-muted-foreground">
                            Free Result
                          </th>
                          <th className="py-2 text-center font-medium text-primary">
                            Fix Pack
                          </th>
                        </tr>
                      </thead>
                      <tbody className="text-muted-foreground">
                        {[
                          ['Technical AEO Score', 'Yes', 'Yes'],
                          ['AI Readiness Preview', 'Yes', 'Yes'],
                          ['Top Issues', 'Yes', 'Yes'],
                          ['Full Issue List', 'No', 'Yes'],
                          ['Prioritized Repair Order', 'No', 'Yes'],
                          ['Copy-ready Schema', 'No', 'Yes'],
                          ['Answer-ready Content Blocks', 'No', 'Yes'],
                          ['Query Fan-Out Content Gaps', 'No', 'Yes'],
                          ['Copy-ready LLMs.txt Plan', 'No', 'Yes'],
                          ['Markdown Export', 'Free summary', 'Full fix pack'],
                        ].map(([f, free, paid]) => (
                          <tr key={f} className="border-b border-primary/10">
                            <td className="py-1.5">{f}</td>
                            <td className="py-1.5 text-center">{free}</td>
                            <td className="py-1.5 text-center font-medium text-primary">
                              {paid}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  <div className="mt-6 flex flex-col sm:flex-row justify-center gap-3">
                    <button
                      type="button"
                      onClick={handleCheckout}
                      disabled={checkoutLoading}
                      className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground transition-all hover:opacity-90 active:scale-[0.98] disabled:opacity-50"
                    >
                      {checkoutLoading ? (
                        <>
                          <IconLoader2 size={16} className="animate-spin" />{' '}
                          Redirecting to checkout...
                        </>
                      ) : (
                        'Get the repair plan - $19'
                      )}
                    </button>
                    <a
                      href="/ai-search-audit"
                      onClick={() =>
                        trackConversionEvent('aeo_manual_audit_clicked', {
                          url: r.normalizedUrl,
                        })
                      }
                      className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-200 bg-white px-5 py-3 text-sm font-medium text-emerald-700 transition-all hover:border-emerald-300 hover:bg-emerald-50 active:scale-[0.98] dark:border-emerald-800 dark:bg-emerald-950/20 dark:text-emerald-300 dark:hover:bg-emerald-950/40"
                    >
                      Human review - $99
                    </a>
                    <a
                      href="/sample-aeo-report"
                      className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-muted/40 px-5 py-3 text-sm font-medium text-foreground transition-all hover:border-border/80 active:scale-[0.98]"
                    >
                      Preview sample Fix Pack
                    </a>
                    <a
                      href="#free-aeo-summary"
                      className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-muted/40 px-5 py-3 text-sm font-medium text-foreground transition-all hover:border-border/80 active:scale-[0.98]"
                    >
                      Email me the free summary
                    </a>
                  </div>
                </div>

                {/* Lead capture */}
                <div
                  id="free-aeo-summary"
                  className="rounded-2xl border border-border/60 bg-muted/20 p-8"
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
                      <IconMail size={20} className="text-primary" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-foreground">
                        Email me the free AEO summary
                      </h3>
                      <p className="text-sm text-muted-foreground">
                        We'll email the free summary for {r.normalizedUrl}.
                      </p>
                    </div>
                  </div>
                  {leadMessage ? (
                    <div
                      className={`rounded-xl p-3 text-center text-sm ${
                        leadSuccess
                          ? 'bg-emerald-50 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400'
                          : 'bg-amber-50 dark:bg-amber-950/20 text-amber-700 dark:text-amber-400'
                      }`}
                    >
                      {leadMessage}
                    </div>
                  ) : (
                    <form
                      onSubmit={handleLeadSubmit}
                      className="flex flex-col sm:flex-row gap-3"
                    >
                      <input
                        type="email"
                        placeholder="Email"
                        value={leadEmail}
                        onChange={(e) => setLeadEmail(e.target.value)}
                        disabled={leadLoading}
                        className="flex-1 rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-50"
                      />
                      <input
                        type="url"
                        placeholder="Website URL"
                        value={leadWebsiteUrl}
                        onChange={(e) => setLeadWebsiteUrl(e.target.value)}
                        disabled={leadLoading}
                        className="flex-1 rounded-xl border border-border bg-background px-4 py-2.5 text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-50"
                      />
                      <button
                        type="submit"
                        disabled={leadLoading}
                        className="inline-flex items-center justify-center gap-2 rounded-xl bg-foreground px-5 py-2.5 text-sm font-semibold text-background transition-all hover:opacity-90 active:scale-[0.98] disabled:opacity-50"
                      >
                        {leadLoading ? (
                          <>
                            <IconLoader2 size={14} className="animate-spin" />{' '}
                            Sending...
                          </>
                        ) : (
                          'Send me the report'
                        )}
                      </button>
                    </form>
                  )}
                </div>
              </div>
            </div>
          </Container>
        </div>
      )}

      {/* Explanation */}
      <section className="border-t border-border/50 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="text-center text-2xl font-bold text-foreground">
              What does this AEO Checker audit?
            </h2>
            <p className="mt-6 text-center text-muted-foreground">
              This tool checks technical and content signals that can make a
              page easier for answer engines and AI search systems to
              understand. It looks at crawlability, LLMs.txt, AI crawler access,
              structured data, answer-ready formatting, entity clarity, and
              trust signals.
            </p>
          </div>
        </Container>
      </section>

      {/* Difference */}
      <section className="border-t border-border/50 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="text-center text-2xl font-bold text-foreground">
              AEO readiness is not the same as AI visibility tracking
            </h2>
            <p className="mt-6 text-center text-muted-foreground">
              This tool does not monitor whether your brand appears in ChatGPT,
              Perplexity, Gemini, Claude, or Google AI Overviews. Instead, it
              checks whether your website has the technical and content
              foundations that may help answer engines understand your pages.
            </p>
          </div>
        </Container>
      </section>

      {/* FAQ */}
      <section className="border-t border-border/50 py-16">
        <Container>
          <div className="mx-auto max-w-2xl">
            <h2 className="text-center text-2xl font-bold text-foreground">
              Frequently Asked Questions
            </h2>
            <FAQ items={faqItems} className="mt-8" />
          </div>
        </Container>
      </section>

      {/* Internal links */}
      <section className="border-t border-border/50 py-12">
        <Container>
          <div className="mx-auto max-w-xl text-center">
            <p className="text-sm text-muted-foreground">
              Also try our{' '}
              <a
                href="/tools/llms-txt-checker"
                className="text-primary hover:underline"
              >
                LLMs.txt Checker
              </a>
              ,{' '}
              <a
                href="/tools/llms-txt-generator"
                className="text-primary hover:underline"
              >
                LLMs.txt Generator
              </a>
              ,{' '}
              <a
                href="/tools/query-fan-out-tool"
                className="text-primary hover:underline"
              >
                Query Fan-Out Tool
              </a>
              ,{' '}
              <a
                href="/tools/geo-audit"
                className="text-primary hover:underline"
              >
                GEO Audit Tool
              </a>
              , and{' '}
              <a href="/playbooks" className="text-primary hover:underline">
                AI Search Readiness Playbooks
              </a>
              .
            </p>
          </div>
        </Container>
      </section>

      {/* Trust disclaimer */}
      <section className="border-t border-border/50 py-12">
        <Container>
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm text-muted-foreground">
              This AEO Checker provides a technical readiness audit. It does not
              guarantee rankings or citations, traffic, or visibility in
              ChatGPT, Perplexity, Gemini, Claude, Google AI Overviews, or other
              answer engines.
            </p>
          </div>
        </Container>
      </section>

      <div className="h-8" />
    </div>
  );
}

// ---------- Sub-components ----------

function DashboardCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-border/60 bg-card p-6">
      {children}
    </div>
  );
}

function DashboardSectionHeader({
  title,
  status = 'neutral',
}: {
  title: string;
  status?: Status;
}) {
  const badge = statusBadge(status);
  return (
    <div className="flex items-center justify-between mb-5">
      <h3 className="font-semibold text-foreground">{title}</h3>
      {status !== 'neutral' && (
        <span
          className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${badge.bg} ${badge.text}`}
        >
          {status === 'good' && <IconCheck size={12} />}
          {status === 'warning' && <IconAlertTriangle size={12} />}
          {status === 'issue' && <IconX size={12} />}
          {status.charAt(0).toUpperCase() + status.slice(1)}
        </span>
      )}
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <span className="text-xs text-muted-foreground">{label}</span>
      <p className="text-sm text-foreground break-all">{value}</p>
    </div>
  );
}

function IssueList({
  items,
  type,
  className = '',
}: {
  items: string[];
  type: 'warning' | 'error';
  className?: string;
}) {
  const Icon = type === 'error' ? IconX : IconAlertTriangle;
  const colorClass =
    type === 'error'
      ? 'text-red-600 dark:text-red-400'
      : 'text-amber-600 dark:text-amber-400';
  return (
    <ul className={`space-y-1 text-sm ${className}`}>
      {items.map((item) => (
        <li key={item} className="flex items-start gap-2">
          <Icon size={14} className={`mt-0.5 shrink-0 ${colorClass}`} />
          <span className="text-muted-foreground">{item}</span>
        </li>
      ))}
    </ul>
  );
}

// ---------- Route export ----------

export const Route = createFileRoute('/tools/aeo-checker')({
  head: () => ({
    ...seo('/tools/aeo-checker', {
      title: 'Free AEO Checker: Audit One Page Before AI Search Edits',
      description:
        'Audit one landing, product, or comparison page before editing it for AI answers. Check crawl access, schema, LLMs.txt, answer blocks, and trust gaps.',
    }),
    scripts: [
      jsonLd(
        softwareApplicationSchema({
          name: 'AEO Checker',
          websiteUrl: getCanonicalUrl('/tools/aeo-checker'),
          longDescription:
            'Free tool that audits one URL for AI search readiness before you edit it: crawlability, LLMs.txt, structured data, entity clarity, trust signals, and answer-ready formatting.',
          startingPrice: '$0',
          keyFeatures: [
            'Technical AEO Score (0-100)',
            'AI crawler & LLMs.txt checks',
            'Structured data validation',
            'Answer-ready content analysis',
            'Prioritized repair recommendations',
            '$19 Fix Pack with implementation handoff',
          ],
        })
      ),
      jsonLd(
        faqSchema([
          {
            q: 'What does the AEO Checker audit?',
            a: 'It checks crawlability, LLMs.txt, AI crawler access, structured data, entity clarity, trust signals, and answer-ready page structure, then gives you a readiness score and prioritized repair recommendations.',
          },
          {
            q: 'Is the AEO Checker really free?',
            a: 'Yes. One page audit is free. If you want copy-ready schema, answer blocks, LLMs.txt guidance, and an implementation handoff, a $19 Fix Pack is available. For human judgment on one important page, a $99 manual audit option exists.',
          },
          {
            q: 'Does AEO guarantee AI search visibility?',
            a: 'No tool can guarantee rankings or citations. The AEO Checker measures readiness signals that search engines and AI systems use to understand your content. It shows you what to repair, not what will rank.',
          },
        ])
      ),
      jsonLd(faqSchema(faqItems)),
      jsonLd(
        breadcrumbSchema([
          { name: 'Home', url: getCanonicalUrl('/') },
          { name: 'AEO Checker', url: getCanonicalUrl('/tools/aeo-checker') },
        ])
      ),
    ],
  }),
  component: AeoCheckerPage,
});
