import {
  breadcrumbSchema,
  faqSchema,
  jsonLd,
  softwareApplicationSchema,
} from '@/lib/ai-visibility-schema';
import { seo } from '@/lib/seo';
import { getCanonicalUrl } from '@/lib/urls';
import { trackConversionEvent } from '@/lib/conversion-events';
import { createFileRoute } from '@tanstack/react-router';
import Container from '@/components/layout/container';
import { FAQ } from '@/components/ai-visibility/faq';
import {
  IconCheck,
  IconX,
  IconAlertTriangle,
  IconLoader2,
  IconMail,
  IconCopy,
  IconDownload,
  IconArrowRight,
} from '@tabler/icons-react';
import { runAeoAudit, type AeoAuditResult } from '@/api/ai-readiness/aeo';
import { submitLeadCapture } from '@/api/ai-readiness/lead';
import { createReportCheckout } from '@/api/ai-readiness/report-checkout';
import { useState } from 'react';

// ---------- Types ----------

type Status = 'good' | 'warning' | 'issue' | 'neutral';

// ---------- Utility helpers ----------

function statusBadge(status: Status) {
  const map: Record<Status, { bg: string; text: string }> = {
    good: {
      bg: 'bg-emerald-100 dark:bg-emerald-900/30',
      text: 'text-emerald-700 dark:text-emerald-400',
    },
    warning: {
      bg: 'bg-amber-100 dark:bg-amber-900/30',
      text: 'text-amber-700 dark:text-amber-400',
    },
    issue: {
      bg: 'bg-red-100 dark:bg-red-900/30',
      text: 'text-red-700 dark:text-red-400',
    },
    neutral: {
      bg: 'bg-gray-100 dark:bg-zinc-800',
      text: 'text-gray-600 dark:text-zinc-400',
    },
  };
  return map[status];
}

function accessBadge(access: string) {
  switch (access) {
    case 'allowed':
      return {
        label: 'Allowed',
        cls: 'text-emerald-600 dark:text-emerald-400',
      };
    case 'blocked':
      return { label: 'Blocked', cls: 'text-red-600 dark:text-red-400' };
    default:
      return { label: 'Unknown', cls: 'text-gray-400 dark:text-zinc-500' };
  }
}

function scoreColor(score: number): string {
  if (score >= 80) return 'text-emerald-500';
  if (score >= 60) return 'text-amber-500';
  return 'text-red-500';
}

const scoreLabels: Record<string, string> = {
  '80-100': 'Strong technical AEO readiness',
  '60-79': 'Good foundation with improvement opportunities',
  '40-59': 'Partial readiness, several important gaps',
  '0-39': 'Weak technical AEO readiness',
};

function scoreLabelText(score: number): string {
  if (score >= 80) return scoreLabels['80-100'];
  if (score >= 60) return scoreLabels['60-79'];
  if (score >= 40) return scoreLabels['40-59'];
  return scoreLabels['0-39'];
}

function formatYesNo(value: boolean): string {
  return value ? 'Yes' : 'No';
}

function buildFreeReportMarkdown(result: AeoAuditResult): string {
  const topIssues = result.recommendations.slice(0, 3);
  const lines = [
    '# Free AI Search Readiness Audit',
    '',
    `Website: ${new URL(result.normalizedUrl).hostname}`,
    `Checked URL: ${result.normalizedUrl}`,
    `Generated at: ${new Date(result.checkedAt).toISOString()}`,
    `Overall Score: ${result.score}/100`,
    `Readiness: ${result.scoreLabel}`,
    '',
    '## Executive Summary',
    '',
    `This free summary shows the technical AEO score, key module status, and the top ${topIssues.length} recommended fixes. It is a technical readiness estimate and does not guarantee rankings, citations, traffic, or visibility in any AI search product.`,
    '',
    '## Top Issues',
    '',
    ...(topIssues.length > 0
      ? topIssues.map((issue, index) => `${index + 1}. ${issue}`)
      : ['No major recommendations were generated by the free checker.']),
    '',
    '## Technical AEO Audit',
    '',
    `- HTTP status: ${result.page.statusCode ? `HTTP ${result.page.statusCode}` : 'Unknown'}`,
    `- Title: ${result.page.title || 'Missing'}`,
    `- Meta description: ${result.page.metaDescription || 'Missing'}`,
    `- Canonical: ${result.page.canonical || 'Missing'}`,
    `- Meta robots: ${result.page.metaRobots || 'Not detected'}`,
    '',
    '## AI Search Files Audit',
    '',
    `- LLMs.txt: ${formatYesNo(result.aiFiles.llmsTxt.exists)}`,
    `- LLMs-full.txt: ${formatYesNo(result.aiFiles.llmsFullTxt.exists)}`,
    `- Sitemap.xml: ${formatYesNo(result.aiFiles.sitemap.exists)}`,
    `- Robots.txt: ${formatYesNo(result.aiFiles.robotsTxt.exists)}`,
    '',
    '## Answer-Ready Content Audit',
    '',
    `- H1 count: ${result.answerReadyContent.h1Count}`,
    `- H2 count: ${result.answerReadyContent.h2Count}`,
    `- FAQ section: ${formatYesNo(result.answerReadyContent.hasFaqSection)}`,
    `- Question headings: ${formatYesNo(result.answerReadyContent.hasQuestionHeadings)}`,
    `- Short answer paragraphs: ${formatYesNo(result.answerReadyContent.hasShortAnswerParagraphs)}`,
    '',
    '## Locked Fix Pack Sections',
    '',
    '- Full issue list',
    '- Prioritized repair order',
    '- Copy-ready schema recommendations',
    '- Answer-ready content rewrite suggestions',
    '- Query fan-out content gap analysis',
    '- LLMs.txt improvement plan',
    '- Downloadable implementation handoff',
    '',
    'These tools provide technical readiness checks. They do not guarantee rankings, citations, traffic, or visibility in ChatGPT, Perplexity, Gemini, Claude, Google AI Overviews, or other AI search products.',
  ];

  return lines.join('\n');
}

// ---------- FAQ items ----------

const faqItems = [
  {
    q: 'What is AEO?',
    a: 'AEO stands for Answer Engine Optimization. It is the practice of optimizing your website content and technical foundations so that answer engines and AI search systems can better understand, extract, and cite your pages.',
  },
  {
    q: 'What does an AEO checker do?',
    a: 'An AEO checker audits your website for the technical and content signals that help answer engines understand your pages. It checks crawlability, structured data, LLMs.txt files, AI crawler access, content structure, entity clarity, and trust signals.',
  },
  {
    q: 'Does this tool check ChatGPT rankings?',
    a: 'No. This tool audits technical AEO readiness signals. It does not check whether your brand appears in ChatGPT, Perplexity, or any other AI search product, and does not track rankings or citations.',
  },
  {
    q: 'What is a good AEO score?',
    a: 'A score of 80 or above indicates strong technical readiness. 60-79 shows a good foundation with room to improve. Below 60 means there are several gaps worth addressing. The score is a technical estimate, not a ranking guarantee.',
  },
  {
    q: 'Does LLMs.txt improve AEO?',
    a: 'An LLMs.txt file gives AI systems a structured summary of your site. It is one component of AEO readiness, alongside structured data, crawlability, and content formatting. It helps, but it is not the whole picture.',
  },
  {
    q: 'What structured data helps AEO?',
    a: 'JSON-LD schema types like Organization, WebSite, Article, FAQPage, Product, and HowTo help answer engines understand what your pages are about. The checker identifies which schema types are present and recommends additions.',
  },
  {
    q: 'How is AEO different from SEO?',
    a: 'SEO optimizes for search engine rankings and traffic. AEO optimizes for answer engine understanding and citation. They overlap but are not the same. A page can rank well on Google but still not be structured well for AI extraction.',
  },
];

const heroProofPoints = [
  'Free page diagnosis first',
  'Built for landing pages, product pages, and comparison pages',
  '$19 Fix Pack when you need copy-ready edits',
];

const useCases = [
  {
    title: 'Before publishing a new page',
    desc: 'Confirm crawlers, schema, headings, FAQs, and trust signals before the page starts competing for search demand.',
  },
  {
    title: 'Before refreshing an old page',
    desc: 'Find whether the page gives answer engines direct answers, clear entities, and AI-readable support files before you rewrite it.',
  },
  {
    title: 'Before handing work to an operator',
    desc: 'Unlock the Fix Pack for copy-ready schema, LLMs.txt files, content gaps, and a prioritized repair order.',
  },
];

const trustSignals = [
  'No sign-up required for the free scan',
  'One-time $19 checkout',
  'Implementation handoff after purchase',
  'No ranking or citation guarantees',
];

// ---------- Component ----------

function AeoCheckerPage() {
  const [url, setUrl] = useState(() => {
    if (typeof window === 'undefined') return '';
    return new URLSearchParams(window.location.search).get('url') ?? '';
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AeoAuditResult | null>(null);
  const [leadEmail, setLeadEmail] = useState('');
  const [leadWebsiteUrl, setLeadWebsiteUrl] = useState('');
  const [leadLoading, setLeadLoading] = useState(false);
  const [leadMessage, setLeadMessage] = useState<string | null>(null);
  const [leadSuccess, setLeadSuccess] = useState(false);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [reportMessage, setReportMessage] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = url.trim();
    if (!trimmed) {
      setError('Please enter a domain or page URL.');
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    trackConversionEvent('aeo_audit_started', { url: trimmed });
    try {
      const data = await runAeoAudit({ data: { url: trimmed } });
      setResult(data);
      setLeadWebsiteUrl(data.normalizedUrl);
      setLeadMessage(null);
      trackConversionEvent('aeo_audit_completed', {
        url: data.normalizedUrl,
        score: data.score,
      });
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : 'Something went wrong. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  const handleLeadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!leadEmail.trim() || !leadWebsiteUrl.trim() || !result) return;
    setLeadLoading(true);
    setLeadMessage(null);
    try {
      const res = await submitLeadCapture({
        data: {
          email: leadEmail.trim(),
          websiteUrl: leadWebsiteUrl.trim(),
        },
      });
      setLeadMessage(res.message);
      setLeadSuccess(res.success);
      if (res.success) {
        trackConversionEvent('aeo_lead_capture_submitted', {
          url: leadWebsiteUrl.trim(),
        });
        setLeadEmail('');
      }
    } catch {
      setLeadMessage(
        'Unable to send the report at this time. Please try again later.'
      );
      setLeadSuccess(false);
    } finally {
      setLeadLoading(false);
    }
  };

  const handleCheckout = async () => {
    if (!result) return;
    setCheckoutLoading(true);
    setReportMessage(null);
    trackConversionEvent('full_report_checkout_clicked', {
      url: result.normalizedUrl,
      score: result.score,
      price: 19,
    });
    try {
      const res = await createReportCheckout({
        data: {
          resultJson: JSON.stringify(result),
          websiteUrl: result.normalizedUrl,
        },
      });
      if (res.url) {
        trackConversionEvent('full_report_checkout_redirected', {
          url: result.normalizedUrl,
        });
        window.location.href = res.url;
      } else {
        setReportMessage(
          'Payment service returned an empty URL. Please try again.'
        );
        setCheckoutLoading(false);
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown error';
      setReportMessage(`Checkout failed: ${msg}`);
      setCheckoutLoading(false);
    }
  };

  const handleCopySummary = async () => {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(buildFreeReportMarkdown(result));
      setReportMessage('Free report summary copied.');
    } catch {
      setReportMessage('Unable to copy the report summary.');
    }
  };

  const handleDownloadSummary = () => {
    if (!result) return;
    const markdown = buildFreeReportMarkdown(result);
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const href = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = href;
    link.download = `ai-search-readiness-summary-${
      new URL(result.normalizedUrl).hostname
    }.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(href);
    setReportMessage('Free report summary downloaded.');
  };

  const r = result;

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden border-b border-gray-200 dark:border-zinc-800/50">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-white dark:from-blue-950/30 dark:via-zinc-950 dark:to-zinc-950" />
        <Container className="relative py-20 lg:py-28">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-zinc-50 sm:text-4xl lg:text-5xl">
              Audit one page before editing it for AI answers
            </h1>
            <p className="mx-auto mt-4 max-w-xl text-lg leading-relaxed text-gray-500 dark:text-zinc-400">
              Enter a landing page, product page, or comparison page to find the
              crawl, schema, answer-block, LLMs.txt, and trust gaps to fix
              before you ship changes.
            </p>
            <div className="mt-6 flex flex-wrap justify-center gap-x-4 gap-y-2 text-xs text-gray-500 dark:text-zinc-400">
              {heroProofPoints.map((point) => (
                <span key={point} className="inline-flex items-center gap-1.5">
                  <IconCheck size={13} className="text-emerald-500" />
                  {point}
                </span>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* Form */}
      <section className="py-12">
        <Container>
          <form onSubmit={handleSubmit} className="mx-auto max-w-xl">
            <div className="flex gap-3">
              <input
                type="text"
                placeholder="Enter the page URL you plan to fix"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                disabled={loading}
                className="flex-1 rounded-xl border border-gray-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-4 py-3 text-sm text-gray-900 dark:text-zinc-100 placeholder:text-gray-400 dark:placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 disabled:opacity-50"
              />
              <button
                type="submit"
                disabled={loading}
                className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-6 py-3 text-sm font-semibold text-white transition-all hover:bg-gray-800 active:scale-[0.98] disabled:opacity-50 dark:bg-zinc-50 dark:text-gray-900 dark:hover:bg-zinc-200"
              >
                {loading ? (
                  <>
                    <IconLoader2 size={16} className="animate-spin" />{' '}
                    Auditing...
                  </>
                ) : (
                  'Audit this page free'
                )}
              </button>
            </div>
            <p className="mt-3 text-center text-xs text-gray-400 dark:text-zinc-500">
              Free result: score, module status, and top issues. Paid Fix Pack:
              copy-ready schema, LLMs.txt guidance, answer blocks, and a repair
              order.
            </p>
          </form>
        </Container>
      </section>

      {!r && !loading && (
        <>
          <section className="pb-16">
            <Container>
              <div className="mx-auto max-w-4xl">
                <div className="grid gap-4 md:grid-cols-3">
                  {useCases.map((item) => (
                    <div
                      key={item.title}
                      className="rounded-2xl border border-gray-200 bg-gray-50 p-5 dark:border-zinc-800/60 dark:bg-zinc-900/30"
                    >
                      <h2 className="text-base font-semibold text-gray-900 dark:text-zinc-100">
                        {item.title}
                      </h2>
                      <p className="mt-2 text-sm leading-relaxed text-gray-500 dark:text-zinc-400">
                        {item.desc}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </Container>
          </section>

          <section className="border-t border-gray-200 py-14 dark:border-zinc-800/50">
            <Container>
              <div className="mx-auto grid max-w-4xl gap-8 md:grid-cols-[1fr_0.85fr] md:items-center">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-zinc-100">
                    From audit score to page repair
                  </h2>
                  <p className="mt-4 text-sm leading-relaxed text-gray-500 dark:text-zinc-400">
                    Traditional SEO tools tell you rankings, links, and
                    keywords. This checker focuses on the page-level structure
                    AI answer systems need before they can understand your
                    content: crawl access, schema, concise answers, entity
                    clarity, trust pages, and AI-readable files.
                  </p>
                  <a
                    href="/sample-aeo-report"
                    className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-blue-600 hover:underline dark:text-blue-400"
                  >
                    Preview the $19 Fix Pack <IconArrowRight size={14} />
                  </a>
                </div>
                <div className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900/40">
                  <h3 className="font-semibold text-gray-900 dark:text-zinc-100">
                    Trust and purchase boundaries
                  </h3>
                  <ul className="mt-4 space-y-3 text-sm text-gray-600 dark:text-zinc-400">
                    {trustSignals.map((point) => (
                      <li key={point} className="flex items-start gap-2">
                        <IconCheck
                          size={15}
                          className="mt-0.5 shrink-0 text-emerald-500"
                        />
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </Container>
          </section>
        </>
      )}

      {/* Error */}
      {error && (
        <section className="pb-8">
          <Container>
            <div className="mx-auto max-w-xl rounded-2xl border border-red-200 dark:border-red-900/30 bg-red-50 dark:bg-red-950/20 p-4 text-center">
              <p className="text-sm text-red-700 dark:text-red-400">{error}</p>
            </div>
          </Container>
        </section>
      )}

      {/* Loading */}
      {loading && !r && (
        <section className="pb-20">
          <Container>
            <div className="mx-auto max-w-4xl rounded-2xl border border-gray-200 dark:border-zinc-800/60 bg-gray-50 dark:bg-zinc-900/30 p-8 text-center">
              <IconLoader2
                size={48}
                className="mx-auto animate-spin text-blue-500"
              />
              <p className="mt-4 text-sm text-gray-500 dark:text-zinc-400">
                Auditing your page. This may take a few seconds.
              </p>
            </div>
          </Container>
        </section>
      )}

      {/* Report */}
      {r && (
        <section className="pb-20">
          <Container>
            <div className="mx-auto max-w-4xl space-y-6">
              {/* Score */}
              <div className="rounded-2xl border border-gray-200 dark:border-zinc-800/60 bg-gray-50 dark:bg-zinc-900/30 p-8 text-center">
                <p className="text-sm font-medium text-gray-500 dark:text-zinc-400 uppercase tracking-wide">
                  Technical AEO Score
                </p>
                <p className={`mt-2 text-6xl font-bold ${scoreColor(r.score)}`}>
                  {r.score}
                </p>
                <p className="mt-2 text-sm text-gray-500 dark:text-zinc-400">
                  {scoreLabelText(r.score)}
                </p>
                <p className="mt-3 text-xs text-gray-400 dark:text-zinc-500 italic">
                  This score is a technical readiness estimate. It does not
                  guarantee rankings or citations.
                </p>
              </div>

              {/* Crawlability */}
              <Card title="Technical Crawlability" status="good">
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="Status"
                    value={
                      r.page.statusCode ? `HTTP ${r.page.statusCode}` : 'N/A'
                    }
                  />
                  <Meta
                    label="Content Type"
                    value={r.page.contentType || 'N/A'}
                  />
                  <Meta label="Title" value={r.page.title || 'N/A'} />
                  <Meta
                    label="Meta Description"
                    value={r.page.metaDescription || 'N/A'}
                  />
                  <Meta label="Canonical" value={r.page.canonical || 'N/A'} />
                  <Meta
                    label="Meta Robots"
                    value={r.page.metaRobots || 'N/A'}
                  />
                </div>
                {r.page.warnings.length > 0 && (
                  <ul className="mt-4 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.page.warnings.map((w) => (
                      <li key={w} className="flex items-start gap-2">
                        <IconAlertTriangle
                          size={14}
                          className="mt-0.5 shrink-0 text-amber-500"
                        />{' '}
                        {w}
                      </li>
                    ))}
                  </ul>
                )}
              </Card>

              {/* AI Files */}
              <Card
                title="AI Search Files & Crawler Access"
                status={r.aiFiles.llmsTxt.exists ? 'good' : 'issue'}
              >
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="LLMs.txt"
                    value={
                      r.aiFiles.llmsTxt.exists
                        ? `Found (${r.aiFiles.llmsTxt.statusCode})`
                        : 'Not Found'
                    }
                  />
                  <Meta
                    label="LLMs-full.txt"
                    value={
                      r.aiFiles.llmsFullTxt.exists
                        ? `Found (${r.aiFiles.llmsFullTxt.statusCode})`
                        : 'Not Found'
                    }
                  />
                  <Meta
                    label="Sitemap"
                    value={
                      r.aiFiles.sitemap.exists
                        ? `Found (${r.aiFiles.sitemap.statusCode})`
                        : 'Not Found'
                    }
                  />
                  <Meta
                    label="Robots.txt"
                    value={
                      r.aiFiles.robotsTxt.exists
                        ? `Found (${r.aiFiles.robotsTxt.statusCode})`
                        : 'Not Found'
                    }
                  />
                </div>
                {r.aiFiles.robotsTxt.exists && (
                  <div className="mt-4 overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-200 dark:border-zinc-800">
                          <th className="py-2 text-left font-medium text-gray-500 dark:text-zinc-400">
                            Crawler
                          </th>
                          <th className="py-2 text-left font-medium text-gray-500 dark:text-zinc-400">
                            User Agent
                          </th>
                          <th className="py-2 text-right font-medium text-gray-500 dark:text-zinc-400">
                            Access
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {r.aiFiles.robotsTxt.crawlers.map((c) => {
                          const b = accessBadge(c.access);
                          return (
                            <tr
                              key={c.userAgent}
                              className="border-b border-gray-100 dark:border-zinc-800/50"
                            >
                              <td className="py-2.5 text-gray-700 dark:text-zinc-300">
                                {c.name}
                              </td>
                              <td className="py-2.5 font-mono text-xs text-gray-400 dark:text-zinc-500">
                                {c.userAgent}
                              </td>
                              <td
                                className={`py-2.5 text-right font-medium ${b.cls}`}
                              >
                                {b.label}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </Card>

              {/* Structured Data */}
              <Card
                title="Structured Data"
                status={r.structuredData.hasJsonLd ? 'good' : 'issue'}
              >
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="JSON-LD"
                    value={r.structuredData.hasJsonLd ? 'Found' : 'Not Found'}
                  />
                  <Meta
                    label="Schema Types"
                    value={
                      r.structuredData.schemaTypes.length > 0
                        ? r.structuredData.schemaTypes.join(', ')
                        : 'None'
                    }
                  />
                </div>
                {r.structuredData.parseErrors.length > 0 && (
                  <ul className="mt-4 space-y-1 text-sm text-red-600 dark:text-red-400">
                    {r.structuredData.parseErrors.map((e) => (
                      <li key={e}>{e}</li>
                    ))}
                  </ul>
                )}
                {r.structuredData.warnings.length > 0 && (
                  <ul className="mt-2 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.structuredData.warnings.map((w) => (
                      <li key={w} className="flex items-start gap-2">
                        <IconAlertTriangle
                          size={14}
                          className="mt-0.5 shrink-0 text-amber-500"
                        />{' '}
                        {w}
                      </li>
                    ))}
                  </ul>
                )}
              </Card>

              {/* Answer-ready Content */}
              <Card
                title="Answer-ready Content"
                status={r.answerReadyContent.hasFaqSection ? 'good' : 'warning'}
              >
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="H1 Count"
                    value={String(r.answerReadyContent.h1Count)}
                  />
                  <Meta
                    label="H2 Count"
                    value={String(r.answerReadyContent.h2Count)}
                  />
                  <Meta
                    label="H3 Count"
                    value={String(r.answerReadyContent.h3Count)}
                  />
                  <Meta
                    label="FAQ Section"
                    value={
                      r.answerReadyContent.hasFaqSection ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="Question Headings"
                    value={
                      r.answerReadyContent.hasQuestionHeadings
                        ? 'Found'
                        : 'Not Found'
                    }
                  />
                  <Meta
                    label="Lists"
                    value={
                      r.answerReadyContent.hasLists ? 'Present' : 'Not Found'
                    }
                  />
                  <Meta
                    label="Short Answer Paragraphs"
                    value={
                      r.answerReadyContent.hasShortAnswerParagraphs
                        ? 'Present'
                        : 'Not Found'
                    }
                  />
                </div>
                {r.answerReadyContent.issues.length > 0 && (
                  <ul className="mt-4 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.answerReadyContent.issues.map((i) => (
                      <li key={i} className="flex items-start gap-2">
                        <IconX
                          size={14}
                          className="mt-0.5 shrink-0 text-red-500"
                        />{' '}
                        {i}
                      </li>
                    ))}
                  </ul>
                )}
                {r.answerReadyContent.warnings.length > 0 && (
                  <ul className="mt-2 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.answerReadyContent.warnings.map((w) => (
                      <li key={w} className="flex items-start gap-2">
                        <IconAlertTriangle
                          size={14}
                          className="mt-0.5 shrink-0 text-amber-500"
                        />{' '}
                        {w}
                      </li>
                    ))}
                  </ul>
                )}
              </Card>

              {/* Entity Clarity */}
              <Card title="Entity Clarity" status="warning">
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="Inferred Brand"
                    value={r.entityClarity.inferredBrandName || 'N/A'}
                  />
                  <Meta
                    label="og:site_name"
                    value={
                      r.entityClarity.hasOgSiteName ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="Organization Schema"
                    value={
                      r.entityClarity.hasOrganizationSchema
                        ? 'Found'
                        : 'Not Found'
                    }
                  />
                  <Meta
                    label="Brand Mentions"
                    value={String(r.entityClarity.brandMentionCount ?? 0)}
                  />
                </div>
                {r.entityClarity.issues.length > 0 && (
                  <ul className="mt-4 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.entityClarity.issues.map((i) => (
                      <li key={i} className="flex items-start gap-2">
                        <IconX
                          size={14}
                          className="mt-0.5 shrink-0 text-red-500"
                        />{' '}
                        {i}
                      </li>
                    ))}
                  </ul>
                )}
              </Card>

              {/* Trust Signals */}
              <Card
                title="Trust Signals"
                status={r.trustSignals.hasAuthor ? 'good' : 'issue'}
              >
                <div className="grid grid-cols-2 gap-3 text-sm">
                  <Meta
                    label="Author"
                    value={r.trustSignals.hasAuthor ? 'Found' : 'Not Found'}
                  />
                  <Meta
                    label="Published Date"
                    value={
                      r.trustSignals.hasPublishedDate ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="Modified Date"
                    value={
                      r.trustSignals.hasModifiedDate ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="About Link"
                    value={r.trustSignals.hasAboutLink ? 'Found' : 'Not Found'}
                  />
                  <Meta
                    label="Contact Link"
                    value={
                      r.trustSignals.hasContactLink ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="Privacy Link"
                    value={
                      r.trustSignals.hasPrivacyLink ? 'Found' : 'Not Found'
                    }
                  />
                  <Meta
                    label="External Links"
                    value={String(r.trustSignals.externalLinkCount)}
                  />
                </div>
                {r.trustSignals.issues.length > 0 && (
                  <ul className="mt-4 space-y-1 text-sm text-gray-500 dark:text-zinc-400">
                    {r.trustSignals.issues.map((i) => (
                      <li key={i} className="flex items-start gap-2">
                        <IconX
                          size={14}
                          className="mt-0.5 shrink-0 text-red-500"
                        />{' '}
                        {i}
                      </li>
                    ))}
                  </ul>
                )}
              </Card>

              {/* Recommendations */}
              <Card title="Recommended Fixes" status="neutral">
                <ul className="space-y-2 text-sm text-gray-500 dark:text-zinc-400">
                  {r.recommendations.map((rec) => (
                    <li key={rec} className="flex items-start gap-2">
                      <IconAlertTriangle
                        size={14}
                        className="mt-0.5 shrink-0 text-blue-500"
                      />{' '}
                      {rec}
                    </li>
                  ))}
                </ul>
              </Card>

              {/* AI Preview */}
              {r.aiAnalysis && (
                <Card title="AI Readiness Preview" status="neutral">
                  <div className="space-y-4">
                    <p className="text-sm text-gray-700 dark:text-zinc-300">
                      {r.aiAnalysis.summary}
                    </p>

                    {r.aiAnalysis.quickWins.length > 0 && (
                      <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm dark:border-blue-900/40 dark:bg-blue-950/20">
                        <h4 className="font-medium text-blue-700 dark:text-blue-300">
                          One quick win
                        </h4>
                        <p className="mt-1 text-gray-600 dark:text-zinc-400">
                          {r.aiAnalysis.quickWins[0]}
                        </p>
                      </div>
                    )}

                    <p className="text-xs text-gray-400 dark:text-zinc-500">
                      Fix pack includes the complete action plan, copy-ready
                      schema, llms.txt files, content gaps, and implementation
                      notes.
                    </p>
                  </div>
                </Card>
              )}

              {/* Checked info */}
              <div className="text-center">
                <p className="text-xs text-gray-400 dark:text-zinc-500">
                  Checked: {r.normalizedUrl} at{' '}
                  {new Date(r.checkedAt).toLocaleString()}
                </p>
              </div>

              {/* Report export */}
              <div className="rounded-2xl border border-gray-200 dark:border-zinc-800/60 bg-white dark:bg-zinc-950/30 p-6">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-zinc-200">
                      Free report export
                    </h3>
                    <p className="mt-1 max-w-2xl text-sm text-gray-500 dark:text-zinc-400">
                      Copy or download the free Markdown summary. The full
                      report structure is prepared, but detailed fixes, query
                      fan-out content gaps, and full export remain behind the
                      $19 early access flow.
                    </p>
                  </div>
                  <div className="flex shrink-0 flex-col gap-2 sm:flex-row">
                    <button
                      type="button"
                      onClick={handleCopySummary}
                      className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-300 dark:border-zinc-700 bg-gray-100 dark:bg-zinc-900/50 px-4 py-2.5 text-sm font-medium text-gray-700 dark:text-zinc-300 transition-all hover:border-gray-400 dark:hover:border-zinc-600 active:scale-[0.98]"
                    >
                      <IconCopy size={16} />
                      Copy summary
                    </button>
                    <button
                      type="button"
                      onClick={handleDownloadSummary}
                      className="inline-flex items-center justify-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-sm font-semibold text-white transition-all hover:bg-gray-800 active:scale-[0.98] dark:bg-zinc-50 dark:text-gray-900 dark:hover:bg-zinc-200"
                    >
                      <IconDownload size={16} />
                      Download Markdown
                    </button>
                  </div>
                </div>
                {reportMessage ? (
                  <p className="mt-3 text-sm text-gray-500 dark:text-zinc-400">
                    {reportMessage}
                  </p>
                ) : null}
                <div className="mt-5 grid gap-3 text-sm sm:grid-cols-2">
                  {[
                    'Executive Summary',
                    'Technical AEO Audit',
                    'AI Search Files Audit',
                    'Answer-ready Content Audit',
                    'Query Fan-Out Content Gap Analysis',
                    'Prioritized Fixes',
                  ].map((section) => (
                    <div
                      key={section}
                      className="flex items-center gap-2 rounded-xl border border-gray-200 bg-gray-50 px-3 py-2 text-gray-600 dark:border-zinc-800 dark:bg-zinc-900/30 dark:text-zinc-400"
                    >
                      <IconCheck size={14} className="text-emerald-500" />
                      {section}
                    </div>
                  ))}
                </div>
              </div>

              {/* Fix Pack CTA */}
              <div className="rounded-2xl border border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-950/20 p-8 text-center">
                <h3 className="text-xl font-bold text-gray-900 dark:text-zinc-100">
                  Turn this scan into a repair plan for $19
                </h3>
                <p className="mt-2 text-sm text-gray-500 dark:text-zinc-400">
                  We found {r.recommendations.length} issues on this page. The
                  Fix Pack turns the diagnosis into prioritized edits,
                  copy-ready schema, LLMs.txt guidance, answer blocks, and query
                  fan-out gaps.
                </p>

                {/* Free vs Paid comparison */}
                <div className="mt-6 overflow-x-auto">
                  <table className="w-full text-sm text-left">
                    <thead>
                      <tr className="border-b border-blue-200 dark:border-blue-800">
                        <th className="py-2 font-medium text-gray-500 dark:text-zinc-400">
                          Feature
                        </th>
                        <th className="py-2 text-center font-medium text-gray-500 dark:text-zinc-400">
                          Free Result
                        </th>
                        <th className="py-2 text-center font-medium text-blue-700 dark:text-blue-400">
                          Fix Pack
                        </th>
                      </tr>
                    </thead>
                    <tbody className="text-gray-600 dark:text-zinc-400">
                      {[
                        ['Technical AEO Score', 'Yes', 'Yes'],
                        ['AI Readiness Preview', 'Yes', 'Yes'],
                        ['Top 3 Issues', 'Yes', 'Yes'],
                        ['Full Issue List', 'No', 'Yes'],
                        ['Prioritized Repair Order', 'No', 'Yes'],
                        ['Copy-ready Schema', 'No', 'Yes'],
                        ['Answer-ready Content Blocks', 'No', 'Yes'],
                        ['Query Fan-Out Content Gaps', 'No', 'Yes'],
                        ['Copy-ready LLMs.txt Plan', 'No', 'Yes'],
                        ['Markdown Export', 'Free summary', 'Full fix pack'],
                      ].map(([f, free, paid]) => (
                        <tr
                          key={f}
                          className="border-b border-blue-100/50 dark:border-blue-900/30"
                        >
                          <td className="py-1.5">{f}</td>
                          <td className="py-1.5 text-center">{free}</td>
                          <td className="py-1.5 text-center font-medium text-blue-700 dark:text-blue-400">
                            {paid}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="mt-6 flex flex-col sm:flex-row justify-center gap-3">
                  <button
                    type="button"
                    onClick={handleCheckout}
                    disabled={checkoutLoading}
                    className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition-all hover:bg-blue-700 active:scale-[0.98] disabled:opacity-50"
                  >
                    {checkoutLoading ? (
                      <>
                        <IconLoader2 size={16} className="animate-spin" />{' '}
                        Redirecting to checkout...
                      </>
                    ) : (
                      'Get the repair plan - $19'
                    )}
                  </button>
                  <a
                    href="/ai-search-audit"
                    onClick={() =>
                      trackConversionEvent('aeo_manual_audit_clicked', {
                        url: r.normalizedUrl,
                      })
                    }
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-200 bg-white px-5 py-3 text-sm font-medium text-emerald-700 transition-all hover:border-emerald-300 hover:bg-emerald-50 active:scale-[0.98] dark:border-emerald-800 dark:bg-emerald-950/20 dark:text-emerald-300 dark:hover:bg-emerald-950/40"
                  >
                    Human review - $99
                  </a>
                  <a
                    href="/sample-aeo-report"
                    onClick={() =>
                      trackConversionEvent('aeo_sample_report_clicked', {
                        url: r.normalizedUrl,
                      })
                    }
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-blue-200 bg-white px-5 py-3 text-sm font-medium text-blue-700 transition-all hover:border-blue-300 hover:bg-blue-50 active:scale-[0.98] dark:border-blue-800 dark:bg-blue-950/20 dark:text-blue-300 dark:hover:bg-blue-950/40"
                  >
                    Preview sample Fix Pack
                  </a>
                  <a
                    href="#free-aeo-summary"
                    className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-300 dark:border-zinc-700 bg-gray-100 dark:bg-zinc-900/50 px-5 py-3 text-sm font-medium text-gray-700 dark:text-zinc-300 transition-all hover:border-gray-400 dark:hover:border-zinc-600 active:scale-[0.98]"
                  >
                    Email me the free summary
                  </a>
                </div>
              </div>

              {/* Lead capture */}
              <div
                id="free-aeo-summary"
                className="rounded-2xl border border-gray-200 dark:border-zinc-800/60 bg-gray-50 dark:bg-zinc-900/30 p-8"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 dark:bg-blue-600/10">
                    <IconMail
                      size={20}
                      className="text-blue-600 dark:text-blue-400"
                    />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-800 dark:text-zinc-200">
                      Email me the free AEO summary
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-zinc-400">
                      We'll email the free summary for {r.normalizedUrl}.
                    </p>
                  </div>
                </div>
                {leadMessage ? (
                  <div
                    className={`rounded-xl p-3 text-center text-sm ${leadSuccess ? 'bg-emerald-50 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400' : 'bg-amber-50 dark:bg-amber-950/20 text-amber-700 dark:text-amber-400'}`}
                  >
                    {leadMessage}
                  </div>
                ) : (
                  <form
                    onSubmit={handleLeadSubmit}
                    className="flex flex-col sm:flex-row gap-3"
                  >
                    <input
                      type="email"
                      placeholder="Email"
                      value={leadEmail}
                      onChange={(e) => setLeadEmail(e.target.value)}
                      disabled={leadLoading}
                      className="flex-1 rounded-xl border border-gray-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-4 py-2.5 text-sm text-gray-900 dark:text-zinc-100 placeholder:text-gray-400 dark:placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 disabled:opacity-50"
                    />
                    <input
                      type="url"
                      placeholder="Website URL"
                      value={leadWebsiteUrl}
                      onChange={(e) => setLeadWebsiteUrl(e.target.value)}
                      disabled={leadLoading}
                      className="flex-1 rounded-xl border border-gray-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-4 py-2.5 text-sm text-gray-900 dark:text-zinc-100 placeholder:text-gray-400 dark:placeholder:text-zinc-500 focus:outline-none focus:ring-2 focus:ring-blue-500/50 disabled:opacity-50"
                    />
                    <button
                      type="submit"
                      disabled={leadLoading}
                      className="inline-flex items-center justify-center gap-2 rounded-xl bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white transition-all hover:bg-gray-800 active:scale-[0.98] disabled:opacity-50 dark:bg-zinc-50 dark:text-gray-900 dark:hover:bg-zinc-200"
                    >
                      {leadLoading ? (
                        <>
                          <IconLoader2 size={14} className="animate-spin" />{' '}
                          Sending...
                        </>
                      ) : (
                        'Send me the report'
                      )}
                    </button>
                  </form>
                )}
              </div>
            </div>
          </Container>
        </section>
      )}

      {/* Explanation */}
      <section className="border-t border-gray-200 dark:border-zinc-800/50 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="text-center text-2xl font-bold text-gray-900 dark:text-zinc-100">
              What does this AEO Checker audit?
            </h2>
            <p className="mt-6 text-center text-gray-500 dark:text-zinc-400">
              This tool checks technical and content signals that can make a
              page easier for answer engines and AI search systems to
              understand. It looks at crawlability, LLMs.txt, AI crawler access,
              structured data, answer-ready formatting, entity clarity, and
              trust signals.
            </p>
          </div>
        </Container>
      </section>

      {/* Difference */}
      <section className="border-t border-gray-200 dark:border-zinc-800/50 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h2 className="text-center text-2xl font-bold text-gray-900 dark:text-zinc-100">
              AEO readiness is not the same as AI visibility tracking
            </h2>
            <p className="mt-6 text-center text-gray-500 dark:text-zinc-400">
              This tool does not monitor whether your brand appears in ChatGPT,
              Perplexity, Gemini, Claude, or Google AI Overviews. Instead, it
              checks whether your website has the technical and content
              foundations that may help answer engines understand your pages.
            </p>
          </div>
        </Container>
      </section>

      {/* FAQ */}
      <section className="border-t border-gray-200 dark:border-zinc-800/50 py-16">
        <Container>
          <div className="mx-auto max-w-2xl">
            <h2 className="text-center text-2xl font-bold text-gray-900 dark:text-zinc-100">
              Frequently Asked Questions
            </h2>
            <FAQ items={faqItems} className="mt-8" />
          </div>
        </Container>
      </section>

      {/* Internal links */}
      <section className="border-t border-gray-200 dark:border-zinc-800/50 py-12">
        <Container>
          <div className="mx-auto max-w-xl text-center">
            <p className="text-sm text-gray-500 dark:text-zinc-400">
              Also try our{' '}
              <a
                href="/tools/llms-txt-checker"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                LLMs.txt Checker
              </a>
              ,{' '}
              <a
                href="/tools/llms-txt-generator"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                LLMs.txt Generator
              </a>
              ,{' '}
              <a
                href="/tools/query-fan-out-tool"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                Query Fan-Out Tool
              </a>
              ,{' '}
              <a
                href="/tools/geo-audit"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                GEO Audit Tool
              </a>
              ,{' '}
              <a
                href="/tools/ai-overview-readiness-checker"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                AI Overview Readiness Checker
              </a>
              ,{' '}
              <a
                href="/tools/chatgpt-citation-readiness-checker"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                ChatGPT Citation Readiness Checker
              </a>
              ,{' '}
              <a
                href="/playbooks?utm_source=tool&utm_medium=organic&utm_campaign=aeo-checker&utm_content=footer-link"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                AI Search Readiness Playbooks
              </a>
              ,{' '}
              <a
                href="/sample-aeo-report"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                Sample Fix Pack
              </a>
              , and{' '}
              <a
                href="/guides/llms-txt-file"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                LLMs.txt guide
              </a>
              ,{' '}
              <a
                href="/guides/llms-txt-seo"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                LLMs.txt SEO guide
              </a>
              , and{' '}
              <a
                href="/guides/llms-full-txt"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                LLMs-full.txt guide
              </a>
              .
            </p>
          </div>
        </Container>
      </section>

      {/* Trust disclaimer */}
      <section className="border-t border-gray-200 dark:border-zinc-800/50 py-12">
        <Container>
          <div className="mx-auto max-w-2xl text-center">
            <p className="text-sm text-gray-400 dark:text-zinc-500">
              This AEO Checker provides a technical readiness audit. It does not
              guarantee rankings or citations, traffic, or visibility in
              ChatGPT, Perplexity, Gemini, Claude, Google AI Overviews, or other
              answer engines.
            </p>
          </div>
        </Container>
      </section>

      <div className="h-8" />
    </div>
  );
}

// ---------- Sub-components ----------

function Card({
  title,
  status = 'neutral',
  children,
}: {
  title: string;
  status?: Status;
  children: React.ReactNode;
}) {
  const badge = statusBadge(status);
  return (
    <div className="rounded-2xl border border-gray-200 dark:border-zinc-800/60 bg-gray-50 dark:bg-zinc-900/30 p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold text-gray-800 dark:text-zinc-200">
          {title}
        </h3>
        {status !== 'neutral' && (
          <span
            className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ${badge.bg} ${badge.text}`}
          >
            {status === 'good' && <IconCheck size={12} />}
            {status === 'warning' && <IconAlertTriangle size={12} />}
            {status === 'issue' && <IconX size={12} />}
            {status.charAt(0).toUpperCase() + status.slice(1)}
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <span className="text-xs text-gray-400 dark:text-zinc-500">{label}</span>
      <p className="text-gray-700 dark:text-zinc-300 break-all">{value}</p>
    </div>
  );
}

// ---------- Route export ----------

export const Route = createFileRoute('/tools/aeo-checker')({
  head: () => ({
    ...seo('/tools/aeo-checker', {
      title: 'Free AEO Checker: Audit One Page Before AI Search Edits',
      description:
        'Audit one landing, product, or comparison page before editing it for AI answers. Check crawl access, schema, LLMs.txt, answer blocks, and trust gaps.',
    }),
    scripts: [
      jsonLd(
        softwareApplicationSchema({
          name: 'AEO Checker',
          websiteUrl: getCanonicalUrl('/tools/aeo-checker'),
          longDescription:
            'Free tool that audits one URL for AI search readiness before you edit it: crawlability, LLMs.txt, structured data, entity clarity, trust signals, and answer-ready formatting.',
          startingPrice: '$0',
          keyFeatures: [
            'Technical AEO Score (0-100)',
            'AI crawler & LLMs.txt checks',
            'Structured data validation',
            'Answer-ready content analysis',
            'Prioritized repair recommendations',
            '$19 Fix Pack with implementation handoff',
          ],
        })
      ),
      jsonLd(
        faqSchema([
          {
            q: 'What does the AEO Checker audit?',
            a: 'It checks crawlability, LLMs.txt, AI crawler access, structured data, entity clarity, trust signals, and answer-ready page structure, then gives you a readiness score and prioritized repair recommendations.',
          },
          {
            q: 'Is the AEO Checker really free?',
            a: 'Yes. One page audit is free. If you want copy-ready schema, answer blocks, LLMs.txt guidance, and an implementation handoff, a $19 Fix Pack is available. For human judgment on one important page, a $99 manual audit option exists.',
          },
          {
            q: 'Does AEO guarantee AI search visibility?',
            a: 'No tool can guarantee rankings or citations. The AEO Checker measures readiness signals that search engines and AI systems use to understand your content. It shows you what to repair, not what will rank.',
          },
        ])
      ),
      jsonLd(faqSchema(faqItems)),
      jsonLd(
        breadcrumbSchema([
          { name: 'Home', url: getCanonicalUrl('/') },
          { name: 'AEO Checker', url: getCanonicalUrl('/tools/aeo-checker') },
        ])
      ),
    ],
  }),
  component: AeoCheckerPage,
});
