import { createHmac } from 'node:crypto';

const args = new Set(process.argv.slice(2));
const urlArg = process.argv
  .slice(2)
  .find((arg) => arg.startsWith('--url='))
  ?.slice('--url='.length);
const endpoint = urlArg ?? 'http://localhost:3000/api/webhooks/creem';
const allowRemote = args.has('--allow-remote');
const secret = process.env.CREEM_WEBHOOK_SECRET;

if (!secret) {
  throw new Error('CREEM_WEBHOOK_SECRET is required');
}

const url = new URL(endpoint);
const isLocal =
  url.hostname === 'localhost' ||
  url.hostname === '127.0.0.1' ||
  url.hostname === '[::1]';

if (!isLocal && !allowRemote) {
  throw new Error('Refusing remote smoke test without --allow-remote');
}

const now = Date.now();
const requestId = crypto.randomUUID();
const payload = JSON.stringify({
  id: `evt_manual_audit_smoke_${now}`,
  eventType: 'checkout.completed',
  object: {
    id: `chk_manual_audit_smoke_${now}`,
    request_id: requestId,
    metadata: {
      service: 'manual-audit',
      manualAuditOrderId: `ord_manual_audit_smoke_${now}`,
      requestId,
      websiteUrl: 'https://example.com/manual-audit-smoke',
      email: 'ops+manual-audit-smoke@example.com',
      competitors: 'competitor.example',
      notes: 'Smoke test payload generated by pnpm manual-audit:smoke',
    },
  },
});
const signature = createHmac('sha256', secret).update(payload).digest('hex');

const response = await fetch(endpoint, {
  method: 'POST',
  headers: {
    'content-type': 'application/json',
    'creem-signature': signature,
  },
  body: payload,
});

const body = await response.text();
console.log(`POST ${endpoint}`);
console.log(`Status: ${response.status}`);
console.log(body);

if (!response.ok) {
  process.exitCode = 1;
}
