/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToolsQueryFanOutToolRouteImport } from './routes/tools.query-fan-out-tool'
import { Route as ToolsLlmsTxtGeneratorRouteImport } from './routes/tools.llms-txt-generator'
import { Route as ToolsLlmsTxtCheckerRouteImport } from './routes/tools.llms-txt-checker'
import { Route as ToolsAeoCheckerRouteImport } from './routes/tools.aeo-checker'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as GuidesQueryFanOutRouteImport } from './routes/guides.query-fan-out'
import { Route as GuidesLlmsTxtSeoRouteImport } from './routes/guides.llms-txt-seo'
import { Route as GuidesLlmsTxtFileRouteImport } from './routes/guides.llms-txt-file'
import { Route as GuidesLlmsFullTxtRouteImport } from './routes/guides.llms-full-txt'
import { Route as GuidesAeoAuditRouteImport } from './routes/guides.aeo-audit'
import { Route as GlossarySlugRouteImport } from './routes/glossary/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesAiRouteImport } from './routes/(pages)/ai'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsQueryFanOutToolRoute = ToolsQueryFanOutToolRouteImport.update({
  id: '/tools/query-fan-out-tool',
  path: '/tools/query-fan-out-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLlmsTxtGeneratorRoute = ToolsLlmsTxtGeneratorRouteImport.update({
  id: '/tools/llms-txt-generator',
  path: '/tools/llms-txt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLlmsTxtCheckerRoute = ToolsLlmsTxtCheckerRouteImport.update({
  id: '/tools/llms-txt-checker',
  path: '/tools/llms-txt-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAeoCheckerRoute = ToolsAeoCheckerRouteImport.update({
  id: '/tools/aeo-checker',
  path: '/tools/aeo-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesQueryFanOutRoute = GuidesQueryFanOutRouteImport.update({
  id: '/guides/query-fan-out',
  path: '/guides/query-fan-out',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLlmsTxtSeoRoute = GuidesLlmsTxtSeoRouteImport.update({
  id: '/guides/llms-txt-seo',
  path: '/guides/llms-txt-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLlmsTxtFileRoute = GuidesLlmsTxtFileRouteImport.update({
  id: '/guides/llms-txt-file',
  path: '/guides/llms-txt-file',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesLlmsFullTxtRoute = GuidesLlmsFullTxtRouteImport.update({
  id: '/guides/llms-full-txt',
  path: '/guides/llms-full-txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAeoAuditRoute = GuidesAeoAuditRouteImport.update({
  id: '/guides/aeo-audit',
  path: '/guides/aeo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarySlugRoute = GlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAiRoute = pagesAiRouteImport.update({
  id: '/(pages)/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/ai': typeof pagesAiRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/guides/aeo-audit': typeof GuidesAeoAuditRoute
  '/guides/llms-full-txt': typeof GuidesLlmsFullTxtRoute
  '/guides/llms-txt-file': typeof GuidesLlmsTxtFileRoute
  '/guides/llms-txt-seo': typeof GuidesLlmsTxtSeoRoute
  '/guides/query-fan-out': typeof GuidesQueryFanOutRoute
  '/report/$token': typeof ReportTokenRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/aeo-checker': typeof ToolsAeoCheckerRoute
  '/tools/llms-txt-checker': typeof ToolsLlmsTxtCheckerRoute
  '/tools/llms-txt-generator': typeof ToolsLlmsTxtGeneratorRoute
  '/tools/query-fan-out-tool': typeof ToolsQueryFanOutToolRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/ai': typeof pagesAiRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/guides/aeo-audit': typeof GuidesAeoAuditRoute
  '/guides/llms-full-txt': typeof GuidesLlmsFullTxtRoute
  '/guides/llms-txt-file': typeof GuidesLlmsTxtFileRoute
  '/guides/llms-txt-seo': typeof GuidesLlmsTxtSeoRoute
  '/guides/query-fan-out': typeof GuidesQueryFanOutRoute
  '/report/$token': typeof ReportTokenRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/aeo-checker': typeof ToolsAeoCheckerRoute
  '/tools/llms-txt-checker': typeof ToolsLlmsTxtCheckerRoute
  '/tools/llms-txt-generator': typeof ToolsLlmsTxtGeneratorRoute
  '/tools/query-fan-out-tool': typeof ToolsQueryFanOutToolRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/glossary': typeof GlossaryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/ai': typeof pagesAiRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/glossary/$slug': typeof GlossarySlugRoute
  '/guides/aeo-audit': typeof GuidesAeoAuditRoute
  '/guides/llms-full-txt': typeof GuidesLlmsFullTxtRoute
  '/guides/llms-txt-file': typeof GuidesLlmsTxtFileRoute
  '/guides/llms-txt-seo': typeof GuidesLlmsTxtSeoRoute
  '/guides/query-fan-out': typeof GuidesQueryFanOutRoute
  '/report/$token': typeof ReportTokenRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/aeo-checker': typeof ToolsAeoCheckerRoute
  '/tools/llms-txt-checker': typeof ToolsLlmsTxtCheckerRoute
  '/tools/llms-txt-generator': typeof ToolsLlmsTxtGeneratorRoute
  '/tools/query-fan-out-tool': typeof ToolsQueryFanOutToolRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/glossary/': typeof GlossaryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/ai'
    | '/contact'
    | '/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/glossary/$slug'
    | '/guides/aeo-audit'
    | '/guides/llms-full-txt'
    | '/guides/llms-txt-file'
    | '/guides/llms-txt-seo'
    | '/guides/query-fan-out'
    | '/report/$token'
    | '/settings/billing'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/aeo-checker'
    | '/tools/llms-txt-checker'
    | '/tools/llms-txt-generator'
    | '/tools/query-fan-out-tool'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/glossary/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/ai'
    | '/contact'
    | '/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/glossary/$slug'
    | '/guides/aeo-audit'
    | '/guides/llms-full-txt'
    | '/guides/llms-txt-file'
    | '/guides/llms-txt-seo'
    | '/guides/query-fan-out'
    | '/report/$token'
    | '/settings/billing'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/aeo-checker'
    | '/tools/llms-txt-checker'
    | '/tools/llms-txt-generator'
    | '/tools/query-fan-out-tool'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/glossary'
    | '/settings'
    | '/api/auth/$'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/manifest.json'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/ai'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/blog/$slug'
    | '/glossary/$slug'
    | '/guides/aeo-audit'
    | '/guides/llms-full-txt'
    | '/guides/llms-txt-file'
    | '/guides/llms-txt-seo'
    | '/guides/query-fan-out'
    | '/report/$token'
    | '/settings/billing'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/aeo-checker'
    | '/tools/llms-txt-checker'
    | '/tools/llms-txt-generator'
    | '/tools/query-fan-out-tool'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/glossary/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAiRoute: typeof pagesAiRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  ApiPingRoute: typeof ApiPingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GlossarySlugRoute: typeof GlossarySlugRoute
  GuidesAeoAuditRoute: typeof GuidesAeoAuditRoute
  GuidesLlmsFullTxtRoute: typeof GuidesLlmsFullTxtRoute
  GuidesLlmsTxtFileRoute: typeof GuidesLlmsTxtFileRoute
  GuidesLlmsTxtSeoRoute: typeof GuidesLlmsTxtSeoRoute
  GuidesQueryFanOutRoute: typeof GuidesQueryFanOutRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ToolsAeoCheckerRoute: typeof ToolsAeoCheckerRoute
  ToolsLlmsTxtCheckerRoute: typeof ToolsLlmsTxtCheckerRoute
  ToolsLlmsTxtGeneratorRoute: typeof ToolsLlmsTxtGeneratorRoute
  ToolsQueryFanOutToolRoute: typeof ToolsQueryFanOutToolRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/query-fan-out-tool': {
      id: '/tools/query-fan-out-tool'
      path: '/tools/query-fan-out-tool'
      fullPath: '/tools/query-fan-out-tool'
      preLoaderRoute: typeof ToolsQueryFanOutToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/llms-txt-generator': {
      id: '/tools/llms-txt-generator'
      path: '/tools/llms-txt-generator'
      fullPath: '/tools/llms-txt-generator'
      preLoaderRoute: typeof ToolsLlmsTxtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/llms-txt-checker': {
      id: '/tools/llms-txt-checker'
      path: '/tools/llms-txt-checker'
      fullPath: '/tools/llms-txt-checker'
      preLoaderRoute: typeof ToolsLlmsTxtCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/aeo-checker': {
      id: '/tools/aeo-checker'
      path: '/tools/aeo-checker'
      fullPath: '/tools/aeo-checker'
      preLoaderRoute: typeof ToolsAeoCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/query-fan-out': {
      id: '/guides/query-fan-out'
      path: '/guides/query-fan-out'
      fullPath: '/guides/query-fan-out'
      preLoaderRoute: typeof GuidesQueryFanOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/llms-txt-seo': {
      id: '/guides/llms-txt-seo'
      path: '/guides/llms-txt-seo'
      fullPath: '/guides/llms-txt-seo'
      preLoaderRoute: typeof GuidesLlmsTxtSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/llms-txt-file': {
      id: '/guides/llms-txt-file'
      path: '/guides/llms-txt-file'
      fullPath: '/guides/llms-txt-file'
      preLoaderRoute: typeof GuidesLlmsTxtFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/llms-full-txt': {
      id: '/guides/llms-full-txt'
      path: '/guides/llms-full-txt'
      fullPath: '/guides/llms-full-txt'
      preLoaderRoute: typeof GuidesLlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/aeo-audit': {
      id: '/guides/aeo-audit'
      path: '/guides/aeo-audit'
      fullPath: '/guides/aeo-audit'
      preLoaderRoute: typeof GuidesAeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/$slug': {
      id: '/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof GlossarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/ai': {
      id: '/(pages)/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof pagesAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAiRoute: pagesAiRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  ApiPingRoute: ApiPingRoute,
  BlogSlugRoute: BlogSlugRoute,
  GlossarySlugRoute: GlossarySlugRoute,
  GuidesAeoAuditRoute: GuidesAeoAuditRoute,
  GuidesLlmsFullTxtRoute: GuidesLlmsFullTxtRoute,
  GuidesLlmsTxtFileRoute: GuidesLlmsTxtFileRoute,
  GuidesLlmsTxtSeoRoute: GuidesLlmsTxtSeoRoute,
  GuidesQueryFanOutRoute: GuidesQueryFanOutRoute,
  ReportTokenRoute: ReportTokenRoute,
  ToolsAeoCheckerRoute: ToolsAeoCheckerRoute,
  ToolsLlmsTxtCheckerRoute: ToolsLlmsTxtCheckerRoute,
  ToolsLlmsTxtGeneratorRoute: ToolsLlmsTxtGeneratorRoute,
  ToolsQueryFanOutToolRoute: ToolsQueryFanOutToolRoute,
  BlogIndexRoute: BlogIndexRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
